{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
     {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.loadBalancerIP }}
  name: realtime-v1-navigator
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: realtime-v1-navigator{{ .Values.ingress.domainName }}
      http:
        paths:
          - backend:
              serviceName: {{ template "app.name" . }}
              servicePort: {{ .Values.service.http.externalPort }}
  {{- end }}
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.loadBalancerIP }}
  name: realtime-v1-vehicle-position
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: realtime-v1-vehicle-position{{ .Values.ingress.domainName }}
      http:
        paths:
          - backend:
              serviceName: mqtt
              servicePort: 8080
{{- end }}