FROM node:6.10.3
# https://hub.docker.com/_/node/
# Can it run with 7.10.0 ? Or 6.10.3-alpine?

RUN wget --quiet https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64.deb
RUN dpkg -i dumb-init_*.deb

COPY git_navigator_hash.txt /git_navigator_hash.txt

ENV DIR_PATH=/opt/navigatorserver
ENV NODE_OPTS=''
ENV MQTT='mqtt://mqtt:1883'
WORKDIR ${DIR_PATH}
RUN mkdir -p ${DIR_PATH} \
 && npm install grunt-cli
ADD package.json ${DIR_PATH}/package.json
RUN npm install
ADD . ${DIR_PATH}

CMD ["dumb-init", "node", "$NODE_OPTS", "./node_modules/.bin/grunt", "server", "--MQTT", "$MQTT" "--stack" ]
